### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by luanagpinax** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t2-match-game#10]

**Comment by AndreeGS** [comment]
V.3




![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t2-match-game/assets/116499898/95c047b1-2f1a-4180-a90a-2c821fd35992)
