### ISSUE TITLE
Modelo Entidade Relacionamento (Projeto Conceitual)

### ISSUE THREAD

**Issue by luanagpinax** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t2-match-game#13]

**Comment by GabrielBruno7** [comment]
![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t2-match-game/assets/114627827/069c2d8b-dde7-4685-bee5-1cc251ec65b9)
