### ISSUE TITLE
Relatório do teste de usabilidade

### ISSUE THREAD

**Issue by luanagpinax** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t2-match-game#34]
O Relatório de Testes deve explicitar o atendimento aos requisitos funcionais e não funcionais do sistema e é baseado no plano de testes proposto na etapa 2 e desenvolvido durante as etapas 3 e 4.

O Relatório de Testes deve contemplar também os testes de Usabilidade contendo as evidências dos testes e relatos dos usuários participantes, baseado no plano de testes desenvolvido na etapa 2 e nas etapas 3 e 4.

Os relatórios devem ser apresentados nas seções Registro de Testes de Software e Registro de Testes de Usabilidade.

**Comment by brunasantos-dev** [comment]
**Conclusões e recomendações**
Após a análise abrangente da usabilidade da plataforma Match Game, observamos uma experiência geral positiva por parte dos usuários, destacando a interface informativa e a facilidade de interação em determinados aspectos. No entanto, identificamos desafios significativos, principalmente relacionados à navegação em dispositivos móveis e ao processo de cadastro.

Os relatos dos usuários, especialmente aqueles que acessaram a plataforma por meio de dispositivos móveis, evidenciaram dificuldades na navegação, com problemas notáveis ao clicar em links e botões. O cadastro mobile também apresentou obstáculos, com destaque para a complexidade do preenchimento do campo "Data de Nascimento". Essa dificuldade pode impactar negativamente a experiência do usuário, criando barreiras para o registro de novos usuários, buscaremos uma maneira de melhorar a experiência do site nesse sentido.

Sabemos que é crucial priorizar a resolução dos problemas identificados na navegação mobile para garantir uma experiência fluida e eficaz para todos os usuários, independentemente do dispositivo utilizado, então criamos a solução para que todos os botões da header fossem clicáveis e adicionamos a tag alt para descrição das imagens, melhorando a acessibilidade para os nossos usuários e atinjimos os 95% de acessilidade, conforme estipulado pela ferramenta LightHouse.

**Requisitos não funcionais**
Nossa aplicação foi desenvolvida seguindo a abordagem "mobile first", priorizando a responsividade em todas as páginas como um requisito não funcional essencial. Compartilhamos o link de hospedagem na nuvem Azure com oito usuários para testes em diferentes navegadores padrão, incluindo Google Chrome, Internet Explorer, Firefox, Safari, entre outros. O objetivo era certificar que a aplicação fluísse corretamente em todos esses ambientes. Além disso, buscamos adotar o HTML semântico na construção de todas as páginas, garantindo não apenas a funcionalidade, mas também a clareza e a acessibilidade do código.

**Feedback dos usuários**
A coleta contínua de feedback dos usuários é fundamental para manter a relevância e eficácia da plataforma. Estabelecemos o TypeForm como canal eficiente para receber e analisar feedbacks que proporcionará informações valiosas para futuras melhorias.
