### ISSUE TITLE
Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by luanagpinax** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t2-match-game#5]

**Comment by AndreeGS** [comment]
Atualização



![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t2-match-game/assets/116499898/86bba040-dec0-4033-94c0-349f976dae21)
